=pod

=head1 NAME

Fennec::Manual - The Fennec Manual

=head1 MANUAL GUIDE

=over 4

=item QUICKSTART

If you want to jump right into using Fennec without reading the user manual.

L<Fennec::Manual::Quickstart>

=item USER MANUAL

Covers usage of Fennec when writing tests and managing test suites.

L<Fennec::Manual::User>

=item DEVELOPER MANUAL

Guide to developing plugins or enhancements for Fennec.

L<Fennec::Manual::Developer>

=back

=head1 AUTHORS

Chad Granum L<exodist7@gmail.com>

=head1 COPYRIGHT

Copyright (C) 2010 Chad Granum

Fennec is free software; Standard perl licence.

Fennec is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the license for more details.
