#!/usr/bin/perl
use strict;
use warnings;

use Fennec::Runner::Args qw/parse_args/;

if ( grep { m/^-+h(elp)?$/ } @ARGV ) {
    print <<EOT;

USAGE: $0 [prove_args] [-- fennec_args [files...]]

prove args and fennec args must be seperated by '--'

Fennec args:
    -c CASE_NAME
    -d SET_NAME

Will run one of the following in order, placing the fennec arguments in an
environment variable.
    \$ prove [args] ./test.pl
    \$ prove [args] ../test.pl
    \$ prove [args] `which fennec_run.pl`
    \$ prove [args] `script/fennec_run.pl`

EOT
    exit;
}

my @prove_args;
my @fennec_args;

my $seperator;
for my $arg ( @ARGV ) {
    if ( $arg eq '--' ) {
        $seperator++;
    }
    elsif ($seperator) {
        push @fennec_args => $arg;
    }
    else {
        push @prove_args => $arg;
    }
}

my $prove = join(" ", @prove_args);
$prove = "prove $prove ";
if ( -e './test.pl' ) {
    $prove .= "./test.pl"
}
elsif( -e "../test.pl" ) {
    $prove .= "../test.pl"
}
else {
    $prove .= `which fennec_run.pl 2>/dev/null` || 'script/fennec_run.pl';
}

my $fennec = join( " ", @fennec_args );

my $run = "FENNEC_ARGV='$fennec' $prove\n";
print $run;
exec $run;
